/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import jogadores.Goleiro;
import jogadores.JogadorBase;
import jogadores.JogadorDeLinha;
import textFilesApps.CreateTextFile;
import textFilesApps.ReadTextFile;

/**
 *
 * @author Tata_
 */
public class JCriarJogadores extends javax.swing.JFrame {

    private ArrayList<JogadorBase> jogadores;
    private CreateTextFile create;
    private ReadTextFile read;
    
    public JCriarJogadores() throws IOException, FileNotFoundException, ClassNotFoundException {
        read = new ReadTextFile();
        create = new CreateTextFile();
        jogadores = read.buscarJogares();       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botoes = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ata = new javax.swing.JRadioButton();
        pe = new javax.swing.JRadioButton();
        pd = new javax.swing.JRadioButton();
        mei = new javax.swing.JRadioButton();
        me = new javax.swing.JRadioButton();
        md = new javax.swing.JRadioButton();
        mc = new javax.swing.JRadioButton();
        le = new javax.swing.JRadioButton();
        ld = new javax.swing.JRadioButton();
        zag = new javax.swing.JRadioButton();
        gl = new javax.swing.JRadioButton();
        vol = new javax.swing.JRadioButton();
        nome = new javax.swing.JTextField();
        tamanho = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        peso = new javax.swing.JTextField();
        idade = new javax.swing.JTextField();
        criar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Criar Jogador");
        setResizable(false);
        setSize(new java.awt.Dimension(452, 250));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Criar Jogador"));

        jLabel1.setText("Nome do Jogador: ");

        jLabel3.setText("Tamanho: ");

        jLabel4.setText("Peso:");

        jLabel5.setText("Posição:");

        botoes.add(ata);
        ata.setText("ATA");
        ata.setActionCommand("Ata");
        ata.setName("ATA"); // NOI18N

        botoes.add(pe);
        pe.setText("PE");
        pe.setActionCommand("pe");
        pe.setName("PE"); // NOI18N

        botoes.add(pd);
        pd.setText("PD");
        pd.setActionCommand("pd");

        botoes.add(mei);
        mei.setText("MEI");
        mei.setActionCommand("mei");

        botoes.add(me);
        me.setText("ME");
        me.setActionCommand("me");

        botoes.add(md);
        md.setText("MD");
        md.setActionCommand("md");

        botoes.add(mc);
        mc.setText("MC");
        mc.setActionCommand("mc");

        botoes.add(le);
        le.setText("LE");
        le.setActionCommand("le");

        botoes.add(ld);
        ld.setText("LD");
        ld.setActionCommand("ld");

        botoes.add(zag);
        zag.setText("ZAG");
        zag.setActionCommand("zag");

        botoes.add(gl);
        gl.setText("GL");
        gl.setActionCommand("gl");
        gl.setName("GL"); // NOI18N
        gl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                glActionPerformed(evt);
            }
        });

        botoes.add(vol);
        vol.setText("VOL");
        vol.setActionCommand("vol");

        jLabel2.setText("Idade");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(le)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zag))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(gl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ata)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mei)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(me)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(md)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vol)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ld))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nome)
                            .addComponent(tamanho, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(idade)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gl)
                    .addComponent(ata)
                    .addComponent(pe)
                    .addComponent(pd)
                    .addComponent(mei)
                    .addComponent(me)
                    .addComponent(md)
                    .addComponent(mc)
                    .addComponent(vol)
                    .addComponent(ld))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(le)
                    .addComponent(zag))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        criar.setText("Criar");
        criar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(criar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(criar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void criarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarActionPerformed
        JogadorDeLinha jogador;
        String nome, posicao;
        int idade;
        double tamanho, peso;
        
        try{
            String copiaNome = this.nome.getText().replace(" ", "");
            if (copiaNome.length() == 0) {
                throw new Exception();        
            }else{
                nome = this.nome.getText();
            }
            tamanho = Double.parseDouble(this.tamanho.getText());
            peso = Double.parseDouble(this.peso.getText());
            idade = Integer.parseInt(this.idade.getText());
            posicao = this.botoes.getSelection().getActionCommand().toUpperCase();
            if (posicao.equals("GL")) {
                jogadores.add(new Goleiro(nome, idade, peso, tamanho, 0));
                JOptionPane.showMessageDialog(this, "Jogador criado com sucesso");
            }else{
                
                jogador = new JogadorDeLinha(nome, idade, peso, tamanho, 0);
                jogador.getPosicoes().add(posicao);
                jogadores.add(jogador);
                JOptionPane.showMessageDialog(this, "Jogador criado com sucesso");
            }
            
            create.jogadoresCriados(jogadores);           
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Digite apenas valores válidos");
        }
    }//GEN-LAST:event_criarActionPerformed

    private void glActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_glActionPerformed
       
    }//GEN-LAST:event_glActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JCriarJogadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JCriarJogadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JCriarJogadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JCriarJogadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JCriarJogadores().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(JCriarJogadores.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(JCriarJogadores.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ata;
    private javax.swing.ButtonGroup botoes;
    private javax.swing.JButton criar;
    private javax.swing.JRadioButton gl;
    private javax.swing.JTextField idade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton ld;
    private javax.swing.JRadioButton le;
    private javax.swing.JRadioButton mc;
    private javax.swing.JRadioButton md;
    private javax.swing.JRadioButton me;
    private javax.swing.JRadioButton mei;
    private javax.swing.JTextField nome;
    private javax.swing.JRadioButton pd;
    private javax.swing.JRadioButton pe;
    private javax.swing.JTextField peso;
    private javax.swing.JTextField tamanho;
    private javax.swing.JRadioButton vol;
    private javax.swing.JRadioButton zag;
    // End of variables declaration//GEN-END:variables
}
