package textFilesApps;

import java.util.ArrayList;
import jogadores.Goleiro;
import jogadores.JogadorDeLinha;
import time.Time;

public class Configuracoes {

    private ArrayList<Time> timesDefault;
    private ArrayList<Time> times;

    public Configuracoes() {
        timesDefault = new ArrayList<>();
        times = new ArrayList<>();
        configurarTimes();
    }

    public ArrayList<Time> getTimesDefault() {
        return timesDefault;
    }

    public void setTimesDefault(ArrayList<Time> timesDefault) {
        this.timesDefault = timesDefault;
    }

    public ArrayList<Time> getTimes() {
        return times;
    }

    public void setTimes(ArrayList<Time> times) {
        this.times = times;
    }
    
    

    public void configurarTimes() {
        //Criando os times
        Time atleticoM = new Time("Atlético-MG", "CAM", "Arena Independência", 5);
        Time atleticoP = new Time("Athletico-PR", "CAP", "Arena da Baixada", 3);
        Time atleticoG = new Time("Atlético-GO", "AGO", "Castelo do Dragao", 2);
        Time bahia = new Time("Bahia", "BAH", "Arena Fonte Nova", 3);
        Time botafogo = new Time("Botafogo", "BOT", "Estadio Nilton Santos", 3);
        Time ceara = new Time("Ceara SC", "CEA", "Arena Castelao", 3);
        Time corinthians = new Time("Corinthians", "COR", "Arena Corinthias", 4);
        Time coritiba = new Time("Coritiba", "CFC", "Couto Pereira", 2);
        Time flamengo = new Time("Flamengo", "FLA", "Maracana", 5);
        Time fluminense = new Time("Fluminense", "FLU", "Maracana", 4);
        Time fortaleza = new Time("Fortaleza", "FOR", "Arena Castelao", 3);
        Time goias = new Time("Goias", "GOI", "Estadio Serra Dourada", 2);
        Time gremio = new Time("Gremio", "GRE", "Arena do Gremio", 4);
        Time inter = new Time("Internacional", "INT", "Beira-Rio", 5);
        Time palmeiras = new Time("Palmeiras", "PAL", "Allianz Parque", 5);
        Time redBull = new Time("Red Bull Bragantino", "BRA", "Estadio Nabi Abi Chedid", 3);
        Time santos = new Time("Santos", "SAN", "Vila Belmiro", 4);
        Time saoPaulo = new Time("Sao Paulo", "SAO", "Morumbi", 5);
        Time sport = new Time("Sport Recife", "SPO", "Estadio Alder da Costa Carvalho", 3);
        Time vasco = new Time("Vasco da Gama", "VAS", "Sao Januario", 3);
        //Criando os jogadores
        //Galo         
        JogadorDeLinha igor = new JogadorDeLinha("Igor Rabello", 0, 0, 0, 16);
        JogadorDeLinha rever = new JogadorDeLinha("Rever", 0, 0, 0, 4);
        JogadorDeLinha jAlonso = new JogadorDeLinha("J. Alonso", 0, 0, 0, 3);
        JogadorDeLinha guga = new JogadorDeLinha("Guga", 0, 0, 0, 2);
        JogadorDeLinha aFranco = new JogadorDeLinha("A. Franco", 0, 0, 0, 21);
        JogadorDeLinha allan = new JogadorDeLinha("Allan", 0, 0, 0, 29);
        JogadorDeLinha gArana = new JogadorDeLinha("G. Arana", 0, 0, 0, 13);
        JogadorDeLinha savarino = new JogadorDeLinha("J. Savarino", 0, 0, 0, 70);
        JogadorDeLinha sasha = new JogadorDeLinha("Sasha", 0, 0, 0, 18);
        JogadorDeLinha keno = new JogadorDeLinha("Keno", 0, 0, 0, 11);
        igor.getPosicoes().add("ZAG");
        rever.getPosicoes().add("ZAG");
        jAlonso.getPosicoes().add("ZAG");
        guga.getPosicoes().add("MD");
        aFranco.getPosicoes().add("VOL");
        allan.getPosicoes().add("VOL");
        gArana.getPosicoes().add("ME");
        savarino.getPosicoes().add("PD");
        sasha.getPosicoes().add("ATA");
        keno.getPosicoes().add("PE");
        atleticoM.getGoleiros().add(new Goleiro("Everson", 30, 86, 1.92, 31));
        atleticoM.getJogadores().add(igor);
        atleticoM.getJogadores().add(rever);
        atleticoM.getJogadores().add(jAlonso);
        atleticoM.getJogadores().add(guga);
        atleticoM.getJogadores().add(aFranco);
        atleticoM.getJogadores().add(allan);
        atleticoM.getJogadores().add(gArana);
        atleticoM.getJogadores().add(savarino);
        atleticoM.getJogadores().add(sasha);
        atleticoM.getJogadores().add(keno);
        //Athletico-PR

        JogadorDeLinha Erick = new JogadorDeLinha("Erick", 23, 71, 1.78, 26);
        JogadorDeLinha PedroHenrique = new JogadorDeLinha("P. Henrique", 25, 80, 1.88, 34);
        JogadorDeLinha ThiagoHeleno = new JogadorDeLinha("T. Heleno", 32, 95, 1.84, 44);
        JogadorDeLinha Abner = new JogadorDeLinha("Abner", 20, 70, 1.88, 16);
        JogadorDeLinha Wellington = new JogadorDeLinha("Wellington", 29, 70, 1.73, 5);
        JogadorDeLinha Christian = new JogadorDeLinha("Christian", 19, 70, 1.75, 88);
        JogadorDeLinha FernandoCanesin = new JogadorDeLinha("F. Canesin", 28, 68, 1.76, 55);
        JogadorDeLinha Nikão = new JogadorDeLinha("Nikão", 28, 73, 1.74, 11);
        JogadorDeLinha Reinaldo = new JogadorDeLinha("Reinaldo", 19, 73, 1.77, 20);
        JogadorDeLinha Kayzer = new JogadorDeLinha("R. Kayzer", 24, 68, 1.78, 79);
        atleticoP.getGoleiros().add(new Goleiro("Santos", 30, 79, 1.88, 1));
        Erick.getPosicoes().add("LD");
        PedroHenrique.getPosicoes().add("ZAG");
        ThiagoHeleno.getPosicoes().add("ZAG");
        Abner.getPosicoes().add("LE");
        Wellington.getPosicoes().add("VOL");
        Christian.getPosicoes().add("VOL");
        FernandoCanesin.getPosicoes().add("MD");
        Nikão.getPosicoes().add("ATA");
        Reinaldo.getPosicoes().add("ME");
        Kayzer.getPosicoes().add("ATA");
        atleticoP.getJogadores().add(Erick);
        atleticoP.getJogadores().add(PedroHenrique);
        atleticoP.getJogadores().add(ThiagoHeleno);
        atleticoP.getJogadores().add(Abner);
        atleticoP.getJogadores().add(Wellington);
        atleticoP.getJogadores().add(Christian);
        atleticoP.getJogadores().add(FernandoCanesin);
        atleticoP.getJogadores().add(Nikão);
        atleticoP.getJogadores().add(Reinaldo);
        atleticoP.getJogadores().add(Kayzer);

        JogadorDeLinha Gilvan = new JogadorDeLinha("Gilvan", 31, 77, 1.88, 2);
        JogadorDeLinha Oliveira = new JogadorDeLinha("Oliveira", 24, 80, 1.87, 88);
        JogadorDeLinha Dudu = new JogadorDeLinha("Dudu", 23, 75, 1.75, 65);
        JogadorDeLinha Nicolas = new JogadorDeLinha("Nicolas", 23, 70, 1.75, 30);
        JogadorDeLinha WillianMaranhão = new JogadorDeLinha("Willian Maranhão", 24, 80, 1.79, 58);
        JogadorDeLinha MarlonFreitas = new JogadorDeLinha("Marlon Freitas", 25, 78, 1.85, 70);
        JogadorDeLinha Chico = new JogadorDeLinha("Chico", 29, 69, 1.75, 77);
        JogadorDeLinha Janderson = new JogadorDeLinha("Janderson", 21, 61, 1.61, 44);
        JogadorDeLinha Ferrareis = new JogadorDeLinha("G. Ferrareis", 24, 69, 1.77, 20);
        JogadorDeLinha ZéRoberto = new JogadorDeLinha("Zé Roberto", 27, 71, 1.8, 11);
        atleticoG.getGoleiros().add(new Goleiro("Jean", 25, 79, 1.88, 1));
        Gilvan.getPosicoes().add("LD");
        Oliveira.getPosicoes().add("ZAG");
        Dudu.getPosicoes().add("ZAG");
        Nicolas.getPosicoes().add("LE");
        WillianMaranhão.getPosicoes().add("VOL");
        MarlonFreitas.getPosicoes().add("VOL");
        Chico.getPosicoes().add("PD");
        Janderson.getPosicoes().add("PE");
        Ferrareis.getPosicoes().add("MEI");
        ZéRoberto.getPosicoes().add("ATA");
        atleticoG.getJogadores().add(Gilvan);
        atleticoG.getJogadores().add(Oliveira);
        atleticoG.getJogadores().add(Dudu);
        atleticoG.getJogadores().add(Nicolas);
        atleticoG.getJogadores().add(WillianMaranhão);
        atleticoG.getJogadores().add(MarlonFreitas);
        atleticoG.getJogadores().add(Chico);
        atleticoG.getJogadores().add(Janderson);
        atleticoG.getJogadores().add(Ferrareis);
        atleticoG.getJogadores().add(ZéRoberto);

        JogadorDeLinha NinoParaíba = new JogadorDeLinha("Nino Paraíba", 34, 62, 1.68, 2);
        JogadorDeLinha Ernando = new JogadorDeLinha("Ernando", 32, 80, 1.84, 14);
        JogadorDeLinha Juninho = new JogadorDeLinha("Juninho", 25, 80, 1.86, 40);
        JogadorDeLinha JuninhoCapixaba = new JogadorDeLinha("Juninho Capixaba", 23, 63, 1.76, 29);
        JogadorDeLinha Gregore = new JogadorDeLinha("Gregore", 26, 78, 1.81, 26);
        JogadorDeLinha Ronaldo = new JogadorDeLinha("Ronaldo", 24, 69, 1.79, 16);
        JogadorDeLinha Rodriguinho = new JogadorDeLinha("Rodriguinho", 32, 69, 1.77, 10);
        JogadorDeLinha Élber = new JogadorDeLinha("Élber", 28, 65, 1.7, 7);
        JogadorDeLinha Rossi = new JogadorDeLinha("Rossi", 27, 69, 1.7, 11);
        JogadorDeLinha Gilberto = new JogadorDeLinha("Gilberto", 31, 70, 1.78, 9);
        bahia.getGoleiros().add(new Goleiro("Douglas Friedrich", 31, 75, 1.94, 1));
        NinoParaíba.getPosicoes().add("LD");
        Ernando.getPosicoes().add("ZAG");
        Juninho.getPosicoes().add("ZAG");
        JuninhoCapixaba.getPosicoes().add("LE");
        Gregore.getPosicoes().add("VOL");
        Ronaldo.getPosicoes().add("VOL");
        Rodriguinho.getPosicoes().add("MEI");
        Élber.getPosicoes().add("PD");
        Rossi.getPosicoes().add("PE");
        Gilberto.getPosicoes().add("ATA");
        bahia.getJogadores().add(NinoParaíba);
        bahia.getJogadores().add(Ernando);
        bahia.getJogadores().add(Juninho);
        bahia.getJogadores().add(JuninhoCapixaba);
        bahia.getJogadores().add(Gregore);
        bahia.getJogadores().add(Ronaldo);
        bahia.getJogadores().add(Rodriguinho);
        bahia.getJogadores().add(Élber);
        bahia.getJogadores().add(Rossi);
        bahia.getJogadores().add(Gilberto);

        JogadorDeLinha MarceloBenevenuto = new JogadorDeLinha("Marcelo Benevenuto", 24, 78, 1.8, 14);
        JogadorDeLinha Kanu = new JogadorDeLinha("Kanu", 23, 74, 1.86, 3);
        JogadorDeLinha VictorLuis = new JogadorDeLinha("Victor Luis", 27, 76, 1.8, 6);
        JogadorDeLinha JoseWelison = new JogadorDeLinha("José Welison", 25, 81, 1.77, 50);
        JogadorDeLinha CaioAlexandre = new JogadorDeLinha("Caio Alexandre", 21, 70, 1.74, 19);
        JogadorDeLinha Honda = new JogadorDeLinha("Honda", 34, 70, 1.82, 4);
        JogadorDeLinha BrunoNazário = new JogadorDeLinha("Bruno Nazário", 25, 68, 1.78, 10);
        JogadorDeLinha Kalou = new JogadorDeLinha("Kalou", 35, 77, 1.84, 8);
        JogadorDeLinha MatheusBabi = new JogadorDeLinha("Matheus Babi", 23, 75, 1.91, 11);
        JogadorDeLinha MatheusNascimento = new JogadorDeLinha("Matheus Nascimento", 16, 71, 1.82, 39);
        botafogo.getGoleiros().add(new Goleiro("Gatito", 32, 86, 1.91, 1));
        MarceloBenevenuto.getPosicoes().add("LD");
        Kanu.getPosicoes().add("ZAG");
        VictorLuis.getPosicoes().add("ZAG");
        JoseWelison.getPosicoes().add("LE");
        CaioAlexandre.getPosicoes().add("VOL");
        Honda.getPosicoes().add("MC");
        BrunoNazário.getPosicoes().add("MEI");
        Kalou.getPosicoes().add("ATA");
        MatheusBabi.getPosicoes().add("ATA");
        MatheusNascimento.getPosicoes().add("ATA");
        botafogo.getJogadores().add(MarceloBenevenuto);
        botafogo.getJogadores().add(Kanu);
        botafogo.getJogadores().add(VictorLuis);
        botafogo.getJogadores().add(JoseWelison);
        botafogo.getJogadores().add(CaioAlexandre);
        botafogo.getJogadores().add(Honda);
        botafogo.getJogadores().add(BrunoNazário);
        botafogo.getJogadores().add(Kalou);
        botafogo.getJogadores().add(MatheusBabi);
        botafogo.getJogadores().add(MatheusNascimento);

        JogadorDeLinha Eduardo = new JogadorDeLinha("Eduardo", 34, 1.82, 67, 86);
        JogadorDeLinha Tiago = new JogadorDeLinha("Tiago", 30, 89, 1.9, 3);
        JogadorDeLinha EduardoBrock = new JogadorDeLinha("Eduardo Brock", 29, 82, 1.86, 4);
        JogadorDeLinha BrunoPacheco = new JogadorDeLinha("Bruno Pacheco", 28, 70, 1.75, 6);
        JogadorDeLinha PedroNaressi = new JogadorDeLinha("Pedro Naressi", 22, 64, 1.70, 44);
        JogadorDeLinha Charles = new JogadorDeLinha("Charles", 24, 76, 1.87, 35);
        JogadorDeLinha Vina = new JogadorDeLinha("Vina", 29, 75, 1.77, 29);
        JogadorDeLinha FernandoSobral = new JogadorDeLinha("Fernando Sobral", 25, 70, 1.78, 88);
        JogadorDeLinha LéoChú = new JogadorDeLinha("Léo Chú", 20, 70, 1.78, 26);
        JogadorDeLinha Cléber = new JogadorDeLinha("Cléber", 24, 1.95, 70, 89);
        ceara.getGoleiros().add(new Goleiro("Fernando Prass", 42, 79, 1.91, 1));
        Eduardo.getPosicoes().add("LD");
        Tiago.getPosicoes().add("ZAG");
        EduardoBrock.getPosicoes().add("ZAG");
        BrunoPacheco.getPosicoes().add("LE");
        PedroNaressi.getPosicoes().add("VOL");
        Charles.getPosicoes().add("VOL");
        Vina.getPosicoes().add("MEI");
        FernandoSobral.getPosicoes().add("PD");
        LéoChú.getPosicoes().add("PE");
        Cléber.getPosicoes().add("ATA");
        ceara.getJogadores().add(Eduardo);
        ceara.getJogadores().add(Tiago);
        ceara.getJogadores().add(EduardoBrock);
        ceara.getJogadores().add(BrunoPacheco);
        ceara.getJogadores().add(PedroNaressi);
        ceara.getJogadores().add(Charles);
        ceara.getJogadores().add(Vina);
        ceara.getJogadores().add(FernandoSobral);
        ceara.getJogadores().add(LéoChú);
        ceara.getJogadores().add(Cléber);

        JogadorDeLinha MatheusSales = new JogadorDeLinha("Matheus Sales", 25, 69, 1.78, 36);
        JogadorDeLinha NathanSilva = new JogadorDeLinha("Nathan Silva", 23, 79, 1.82, 5);
        JogadorDeLinha Sabino = new JogadorDeLinha("Sabino", 24, 88, 1.84, 35);
        JogadorDeLinha WilliamMatheus = new JogadorDeLinha("William Matheus", 30, 73, 1.87, 6);
        JogadorDeLinha HugoMoura = new JogadorDeLinha("Hugo Moura", 22, 73, 1.77, 98);
        JogadorDeLinha MatheusGaldezani = new JogadorDeLinha("Matheus Galdezani", 28, 73, 1.79, 20);
        JogadorDeLinha GiovanniAugusto = new JogadorDeLinha("Giovanni Augusto", 31, 65, 1.75, 90);
        JogadorDeLinha Robson = new JogadorDeLinha("Robson", 29, 75, 1.79, 30);
        JogadorDeLinha Neílton = new JogadorDeLinha("Neílton", 26, 57, 1.66, 10);
        JogadorDeLinha RicardoOliveira = new JogadorDeLinha("Ricardo Oliveira", 40, 78, 1.83, 9);
        coritiba.getGoleiros().add(new Goleiro("Wilson", 36, 83, 1.85, 84));
        MatheusSales.getPosicoes().add("LD");
        NathanSilva.getPosicoes().add("ZAG");
        Sabino.getPosicoes().add("ZAG");
        WilliamMatheus.getPosicoes().add("LE");
        HugoMoura.getPosicoes().add("VOL");
        MatheusGaldezani.getPosicoes().add("VOL");
        GiovanniAugusto.getPosicoes().add("MEI");
        Robson.getPosicoes().add("PD");
        Neílton.getPosicoes().add("PE");
        RicardoOliveira.getPosicoes().add("ATA");
        coritiba.getJogadores().add(MatheusSales);
        coritiba.getJogadores().add(NathanSilva);
        coritiba.getJogadores().add(Sabino);
        coritiba.getJogadores().add(WilliamMatheus);
        coritiba.getJogadores().add(HugoMoura);
        coritiba.getJogadores().add(MatheusGaldezani);
        coritiba.getJogadores().add(GiovanniAugusto);
        coritiba.getJogadores().add(Robson);
        coritiba.getJogadores().add(Neílton);
        coritiba.getJogadores().add(RicardoOliveira);

        JogadorDeLinha Fagner = new JogadorDeLinha("Fagner", 31, 67, 1.68, 3);
        JogadorDeLinha BrunoMéndez = new JogadorDeLinha("Bruno Méndez", 21, 77, 1.84, 14);
        JogadorDeLinha Gil = new JogadorDeLinha("Gil", 33, 89, 1.93, 4);
        JogadorDeLinha FábioSantos = new JogadorDeLinha("Fábio Santos", 35, 76, 1.79, 26);
        JogadorDeLinha Gabriel = new JogadorDeLinha("Gabriel", 28, 69, 1.7, 5);
        JogadorDeLinha Ramiro = new JogadorDeLinha("Ramiro", 27, 67, 1.68, 8);
        JogadorDeLinha Cazares = new JogadorDeLinha("Cazares", 28, 63, 1.71, 10);
        JogadorDeLinha Luan = new JogadorDeLinha("Luan", 27, 71, 1.8, 7);
        JogadorDeLinha LéoNatel = new JogadorDeLinha("Léo Natel", 23, 73, 1.79, 18);
        JogadorDeLinha Jô = new JogadorDeLinha("Jô", 33, 78, 1.89, 77);
        corinthians.getGoleiros().add(new Goleiro("Cássio", 33, 70, 1.96, 12));
        Fagner.getPosicoes().add("LD");
        BrunoMéndez.getPosicoes().add("ZAG");
        Gil.getPosicoes().add("ZAG");
        FábioSantos.getPosicoes().add("LD");
        Gabriel.getPosicoes().add("VOL");
        Ramiro.getPosicoes().add("MC");
        Cazares.getPosicoes().add("MEI");
        Luan.getPosicoes().add("PD");
        LéoNatel.getPosicoes().add("PE");
        Jô.getPosicoes().add("ATA");
        corinthians.getJogadores().add(Fagner);
        corinthians.getJogadores().add(BrunoMéndez);
        corinthians.getJogadores().add(Gil);
        corinthians.getJogadores().add(FábioSantos);
        corinthians.getJogadores().add(Gabriel);
        corinthians.getJogadores().add(Ramiro);
        corinthians.getJogadores().add(Cazares);
        corinthians.getJogadores().add(Luan);
        corinthians.getJogadores().add(LéoNatel);
        corinthians.getJogadores().add(Jô);

        JogadorDeLinha Isla = new JogadorDeLinha("Isla", 32, 75, 1.76, 44);
        JogadorDeLinha RodrigoCaio = new JogadorDeLinha("Rodrigo Caio", 27, 70, 1.82, 3);
        JogadorDeLinha LéoPereira = new JogadorDeLinha("Léo Pereira", 24, 76, 1.89, 4);
        JogadorDeLinha FilipeLuís = new JogadorDeLinha("Filipe Luís", 35, 73, 1.82, 16);
        JogadorDeLinha WillianArão = new JogadorDeLinha("Willian Arão", 28, 74, 1.81, 5);
        JogadorDeLinha Gérson = new JogadorDeLinha("Gérson", 23, 66, 1.88, 8);
        JogadorDeLinha EvertonRibeiro = new JogadorDeLinha("Everton Ribeiro", 31, 69, 1.74, 7);
        JogadorDeLinha Arrascaeta = new JogadorDeLinha("Arrascaeta", 26, 67, 1.72, 14);
        JogadorDeLinha BrunoHenrique = new JogadorDeLinha("Bruno Henrique", 29, 71, 1.85, 27);
        JogadorDeLinha GabrielBarbosa = new JogadorDeLinha("Gabriel Barbosa", 24, 68, 1.78, 9);
        flamengo.getGoleiros().add(new Goleiro("Diego Alves", 35, 85, 1.88, 1));
        Isla.getPosicoes().add("LD");
        RodrigoCaio.getPosicoes().add("ZAG");
        LéoPereira.getPosicoes().add("ZAG");
        FilipeLuís.getPosicoes().add("LE");
        WillianArão.getPosicoes().add("VOL");
        Gérson.getPosicoes().add("VOL");
        EvertonRibeiro.getPosicoes().add("MEI");
        Arrascaeta.getPosicoes().add("MEI");
        BrunoHenrique.getPosicoes().add("ATA");
        GabrielBarbosa.getPosicoes().add("ATA");
        flamengo.getJogadores().add(Isla);
        flamengo.getJogadores().add(RodrigoCaio);
        flamengo.getJogadores().add(LéoPereira);
        flamengo.getJogadores().add(FilipeLuís);
        flamengo.getJogadores().add(WillianArão);
        flamengo.getJogadores().add(Gérson);
        flamengo.getJogadores().add(EvertonRibeiro);
        flamengo.getJogadores().add(Arrascaeta);
        flamengo.getJogadores().add(BrunoHenrique);
        flamengo.getJogadores().add(GabrielBarbosa);

        JogadorDeLinha IgorJulião = new JogadorDeLinha("I. Julião", 26, 62, 1.75, 21);
        JogadorDeLinha Nino = new JogadorDeLinha("Nino", 23, 79, 1.88, 33);
        JogadorDeLinha Digão = new JogadorDeLinha("Digão", 32, 85, 1.87, 26);
        JogadorDeLinha DaniloBarcelos = new JogadorDeLinha("D. Barcelos", 29, 75, 1.86, 14);
        JogadorDeLinha Hudson = new JogadorDeLinha("Hudson", 32, 75, 1.79, 25);
        JogadorDeLinha Dodi = new JogadorDeLinha("Dodo", 24, 60, 1.75, 22);
        JogadorDeLinha Nenê = new JogadorDeLinha("Nenê", 39, 80, 1.81, 39);
        JogadorDeLinha LuizHenrique = new JogadorDeLinha("L. Henrique", 19, 66, 1.75, 34);
        JogadorDeLinha Fred = new JogadorDeLinha("Fred", 37, 87, 1.85, 9);
        JogadorDeLinha MichelAraújo = new JogadorDeLinha("M. Araújo", 24, 74, 1.78, 15);
        fluminense.getGoleiros().add(new Goleiro("Muriel", 33, 78, 1.9, 27));
        IgorJulião.getPosicoes().add("LD");
        Nino.getPosicoes().add("ZAG");
        Digão.getPosicoes().add("ZAG");
        DaniloBarcelos.getPosicoes().add("LE");
        Hudson.getPosicoes().add("VOL");
        Dodi.getPosicoes().add("VOL");
        Nenê.getPosicoes().add("MEI");
        LuizHenrique.getPosicoes().add("PD");
        Fred.getPosicoes().add("ATA");
        MichelAraújo.getPosicoes().add("PE");
        fluminense.getJogadores().add(IgorJulião);
        fluminense.getJogadores().add(Nino);
        fluminense.getJogadores().add(Digão);
        fluminense.getJogadores().add(DaniloBarcelos);
        fluminense.getJogadores().add(Hudson);
        fluminense.getJogadores().add(Dodi);
        fluminense.getJogadores().add(Nenê);
        fluminense.getJogadores().add(LuizHenrique);
        fluminense.getJogadores().add(Fred);
        fluminense.getJogadores().add(MichelAraújo);
//------------------------------------------------------------------------------------------------------------------------------
        //Fortaleza
       	JogadorDeLinha Paulao = new JogadorDeLinha("Paulao", 34, 82, 1.87, 25);
        JogadorDeLinha BrunoMelo = new JogadorDeLinha("B. Melo", 28, 72, 1.83, 30);
        JogadorDeLinha GabrielDias = new JogadorDeLinha("Gabriel Dias", 26, 73, 1.79, 13);
        JogadorDeLinha Carlinhos = new JogadorDeLinha("Carlinhos", 33, 71, 1.67, 6);
        JogadorDeLinha Ronald = new JogadorDeLinha("Ronald", 23, 74, 1.71, 14);
        JogadorDeLinha juninho = new JogadorDeLinha("Juninho", 34, 65, 1.75, 5);
        JogadorDeLinha Marlon = new JogadorDeLinha("Marlon", 30, 68, 1.75, 28);
        JogadorDeLinha Romarinho = new JogadorDeLinha("Romarinho", 26, 66, 1.68, 20);
        JogadorDeLinha David = new JogadorDeLinha("David", 25, 71, 1.79, 17);
        JogadorDeLinha WellingtonPaulista = new JogadorDeLinha("Wellington Paulista", 37, 73, 1.83, 9);
        Paulao.getPosicoes().add("ZAG");
        BrunoMelo.getPosicoes().add("ZAG");
        GabrielDias.getPosicoes().add("PD");
        Carlinhos.getPosicoes().add("PE");
        Ronald.getPosicoes().add("ME");
        juninho.getPosicoes().add("ME");
        Marlon.getPosicoes().add("ME");
        Romarinho.getPosicoes().add("ATA");
        David.getPosicoes().add("ATA");
        WellingtonPaulista.getPosicoes().add("ATA");   
        fortaleza.getGoleiros().add(new Goleiro("Felipe Alves", 32, 86, 1.87, 12));
        fortaleza.getJogadores().add(Paulao);
        fortaleza.getJogadores().add(BrunoMelo);
        fortaleza.getJogadores().add(GabrielDias);
        fortaleza.getJogadores().add(Carlinhos);
        fortaleza.getJogadores().add(Ronald);
        fortaleza.getJogadores().add(juninho);
        fortaleza.getJogadores().add(Marlon);
        fortaleza.getJogadores().add(Romarinho);
        fortaleza.getJogadores().add(David);
        fortaleza.getJogadores().add(WellingtonPaulista);

	//Goias
	JogadorDeLinha JuanPintado = new JogadorDeLinha("Juan Pintado", 23, 62, 1.73, 2);
        JogadorDeLinha chico = new JogadorDeLinha("Chico", 33, 86, 1.86, 55);
        JogadorDeLinha DavidDuarte = new JogadorDeLinha("David Duarte", 25, 84, 1.92, 3);
        JogadorDeLinha Caju = new JogadorDeLinha("Caju", 25, 70, 1.85, 6);
        JogadorDeLinha ArielCabral = new JogadorDeLinha("Ariel Cabral", 33, 76, 1.85, 16);
        JogadorDeLinha Salazar = new JogadorDeLinha("Salazar", 25, 79, 1.80, 20);
        JogadorDeLinha marlon = new JogadorDeLinha("Marlon", 30, 68, 1.75, 28);
        JogadorDeLinha BrenoWashington = new JogadorDeLinha("Breno Washington", 20, 66, 1.77, 5);
        JogadorDeLinha DouglasBaggio = new JogadorDeLinha("Douglas Baggio", 25, 71, 1.72, 95);
        JogadorDeLinha Fernandao = new JogadorDeLinha("Fernandão", 33, 81, 1.80, 99);
        JuanPintado.getPosicoes().add("ME");
        chico.getPosicoes().add("ZAG");
        DavidDuarte.getPosicoes().add("ZAG");
        Caju.getPosicoes().add("PE");
        ArielCabral.getPosicoes().add("ME");
        Salazar.getPosicoes().add("ME");
        marlon.getPosicoes().add("ME");
        BrenoWashington.getPosicoes().add("ME");
        DouglasBaggio.getPosicoes().add("ATA");
        Fernandao.getPosicoes().add("ATA");   
        goias.getGoleiros().add(new Goleiro("Tadeu", 28, 81, 1.84, 23));
        goias.getJogadores().add(JuanPintado);
        goias.getJogadores().add(chico);
        goias.getJogadores().add(DavidDuarte);
        goias.getJogadores().add(Caju);
        goias.getJogadores().add(ArielCabral);
        goias.getJogadores().add(Salazar);
        goias.getJogadores().add(marlon);
        goias.getJogadores().add(BrenoWashington);
        goias.getJogadores().add(DouglasBaggio);
        goias.getJogadores().add(Fernandao);

	//Gremio
	JogadorDeLinha Orejuela = new JogadorDeLinha("Orejuela", 25, 71, 1.77, 17);
        JogadorDeLinha DavidBraz = new JogadorDeLinha("David Braz", 33, 82, 1.87, 14);
        JogadorDeLinha Kannemann = new JogadorDeLinha("Kannemann", 29, 77, 1.83, 4);
        JogadorDeLinha BrunoCortez = new JogadorDeLinha("Bruno Cortez", 33, 76, 1.78, 12);
        JogadorDeLinha MatheusHenrique = new JogadorDeLinha("Matheus Henrique", 22, 71, 1.72, 7);
        JogadorDeLinha Darlan = new JogadorDeLinha("Darlan", 22, 66, 1.71, 15);
        JogadorDeLinha LuizFernando = new JogadorDeLinha("Luiz Fernando", 24, 66, 1.78, 33);
        JogadorDeLinha JeanPyerre = new JogadorDeLinha("Jean Pyerre", 22, 72, 1.83, 10);
        JogadorDeLinha Pepe = new JogadorDeLinha("Pepê", 23, 66, 1.75, 25);
        JogadorDeLinha DiegoSouza = new JogadorDeLinha("Diego Souza", 35, 89, 1.86, 29);
        Orejuela.getPosicoes().add("ZAG");
        DavidBraz.getPosicoes().add("ZAG");
        Kannemann.getPosicoes().add("ZAG");
        BrunoCortez.getPosicoes().add("PE");
        MatheusHenrique.getPosicoes().add("ME");
        Darlan.getPosicoes().add("ME");
        LuizFernando.getPosicoes().add("ATA");
        JeanPyerre.getPosicoes().add("ME");
        Pepe.getPosicoes().add("ATA");
        DiegoSouza.getPosicoes().add("ATA");   
        gremio.getGoleiros().add(new Goleiro("Vanderlei", 36, 86, 1.95, 27));
        gremio.getJogadores().add(Orejuela);
        gremio.getJogadores().add(DavidBraz);
        gremio.getJogadores().add(Kannemann);
        gremio.getJogadores().add(BrunoCortez);
        gremio.getJogadores().add(MatheusHenrique);
        gremio.getJogadores().add(Darlan);
        gremio.getJogadores().add(LuizFernando);
        gremio.getJogadores().add(JeanPyerre);
        gremio.getJogadores().add(Pepe);
        gremio.getJogadores().add(DiegoSouza);

	//Internacional
	JogadorDeLinha Rodinei = new JogadorDeLinha("Rodinei", 28, 70, 1.75, 22);
        JogadorDeLinha ZeGabriel = new JogadorDeLinha("Zé Gabriel", 21, 75, 1.84, 35);
        JogadorDeLinha Cuesta = new JogadorDeLinha("Cuesta", 32, 84, 1.87, 15);
        JogadorDeLinha Uendel = new JogadorDeLinha("Uendel", 32, 73, 1.81, 6);
        JogadorDeLinha Dourado = new JogadorDeLinha("Dourado", 26, 80, 1.86, 13);
        JogadorDeLinha Nonato = new JogadorDeLinha("Nonato", 22, 68, 1.75, 33);
        JogadorDeLinha Edenilson = new JogadorDeLinha("Edenílson", 30, 76, 1.75, 8);
        JogadorDeLinha MauricioMagalhaes = new JogadorDeLinha("Maurício Magalhães", 19, 68, 1.74, 27);
        JogadorDeLinha CaioVidal = new JogadorDeLinha("Caio Vidal", 20, 72, 1.72, 0);
        JogadorDeLinha ThiagoGalhardo = new JogadorDeLinha("Thiago Galhardo", 31, 73, 1.83, 17);
        Rodinei.getPosicoes().add("PD");
        ZeGabriel.getPosicoes().add("ME");
        Cuesta.getPosicoes().add("ZAG");
        Uendel.getPosicoes().add("PE");
        Dourado.getPosicoes().add("ME");
        Nonato.getPosicoes().add("ME");
        Edenilson.getPosicoes().add("ME");
        MauricioMagalhaes.getPosicoes().add("ATA");
        CaioVidal.getPosicoes().add("ATA");
        ThiagoGalhardo.getPosicoes().add("ATA");   
        inter.getGoleiros().add(new Goleiro("Marcelo Lomba", 33, 80, 1.88, 12));
        inter.getJogadores().add(Rodinei);
        inter.getJogadores().add(ZeGabriel);
        inter.getJogadores().add(Cuesta);
        inter.getJogadores().add(Uendel);
        inter.getJogadores().add(Dourado);
        inter.getJogadores().add(Nonato);
        inter.getJogadores().add(Edenilson);
        inter.getJogadores().add(MauricioMagalhaes);
        inter.getJogadores().add(CaioVidal);
        inter.getJogadores().add(ThiagoGalhardo);

	//Palmeiras
	JogadorDeLinha LuanGarcia = new JogadorDeLinha("Luan Garcia", 27, 79, 1.88, 13);
        JogadorDeLinha GustavoGomez = new JogadorDeLinha("Gustavo Gómez", 27, 85, 1.85, 15);
        JogadorDeLinha FelipeMelo = new JogadorDeLinha("Felipe Melo", 20, 78, 1.77, 25);
        JogadorDeLinha GabrielMenino = new JogadorDeLinha("Gabriel Menino", 32, 73, 1.81, 6);
        JogadorDeLinha Danilo = new JogadorDeLinha("Danilo", 19, 0, 0, 0);
        JogadorDeLinha ZeRafael = new JogadorDeLinha("Zé Rafael", 27, 71, 1.75, 8);
        JogadorDeLinha PatrickDePaula = new JogadorDeLinha("Patrick de Paula", 21, 78, 1.8, 5);
        JogadorDeLinha RaphaelVeiga = new JogadorDeLinha("Raphael Veiga", 25, 73, 1.78, 23);
        JogadorDeLinha LucasLima = new JogadorDeLinha("Lucas Lima", 30, 70, 1.75, 20);
        JogadorDeLinha LuizAdriano = new JogadorDeLinha("Luiz Adriano", 33, 76, 1.83, 10);
        LuanGarcia.getPosicoes().add("ZAG");
        GustavoGomez.getPosicoes().add("ZAG");
        FelipeMelo.getPosicoes().add("ME");
        GabrielMenino.getPosicoes().add("PE");
        Danilo.getPosicoes().add("ME");
        ZeRafael.getPosicoes().add("ME");
        PatrickDePaula.getPosicoes().add("ME");
        RaphaelVeiga.getPosicoes().add("ATA");
        LucasLima.getPosicoes().add("ME");
        LuizAdriano.getPosicoes().add("ATA");   
        palmeiras.getGoleiros().add(new Goleiro("Weverton", 32, 89, 1.89, 1));
        palmeiras.getJogadores().add(LuanGarcia);
        palmeiras.getJogadores().add(GustavoGomez);
        palmeiras.getJogadores().add(FelipeMelo);
        palmeiras.getJogadores().add(GabrielMenino);
        palmeiras.getJogadores().add(Danilo);
        palmeiras.getJogadores().add(ZeRafael);
        palmeiras.getJogadores().add(PatrickDePaula);
        palmeiras.getJogadores().add(RaphaelVeiga);
        palmeiras.getJogadores().add(LucasLima);
        palmeiras.getJogadores().add(LuizAdriano);

	//redBull
	JogadorDeLinha RaulLo = new JogadorDeLinha("Raul Lô", 24, 73, 1.80, 23);
        JogadorDeLinha LeoOrtiz = new JogadorDeLinha("Léo Ortiz", 24, 75, 1.86, 3);
        JogadorDeLinha Ligger = new JogadorDeLinha("Ligger", 32, 73, 1.86, 4);
        JogadorDeLinha Edimar = new JogadorDeLinha("Edimar", 34, 73, 1.83, 6);
        JogadorDeLinha Ryller = new JogadorDeLinha("Ryller", 26, 70, 1.76, 25);
        JogadorDeLinha LucasEvangelista = new JogadorDeLinha("Lucas Evangelista", 25, 79, 1.83, 35);
        JogadorDeLinha Claudinho = new JogadorDeLinha("Claudinho", 23, 65, 1.72, 10);
        JogadorDeLinha BrunoTubarao = new JogadorDeLinha("Bruno Tubarão", 25, 70, 1.80, 20);
        JogadorDeLinha ArturVictor = new JogadorDeLinha("Artur Victor", 22, 65, 1.68, 7);
        JogadorDeLinha YtaloJose = new JogadorDeLinha("Ytalo José", 32, 68, 1.77, 15);
        RaulLo.getPosicoes().add("ME");
        LeoOrtiz.getPosicoes().add("ZAG");
        Ligger.getPosicoes().add("ZAG");
        Edimar.getPosicoes().add("PE");
        Ryller.getPosicoes().add("ME");
        LucasEvangelista.getPosicoes().add("ME");
        Claudinho.getPosicoes().add("ATA");
        BrunoTubarao.getPosicoes().add("ATA");
        ArturVictor.getPosicoes().add("ATA");
        YtaloJose.getPosicoes().add("ATA");   
        redBull.getGoleiros().add(new Goleiro("Cleiton", 23, 80, 1.90, 40));
        redBull.getJogadores().add(RaulLo);
        redBull.getJogadores().add(Ligger);
        redBull.getJogadores().add(Edimar);
        redBull.getJogadores().add(Ryller);
        redBull.getJogadores().add(LucasEvangelista);
        redBull.getJogadores().add(ZeRafael);
        redBull.getJogadores().add(Claudinho);
        redBull.getJogadores().add(BrunoTubarao);
        redBull.getJogadores().add(ArturVictor);
        redBull.getJogadores().add(YtaloJose);

	//Santos
	JogadorDeLinha Para = new JogadorDeLinha("Para", 34, 70, 1.73, 4);
        JogadorDeLinha LucasVerissimo = new JogadorDeLinha("Lucas Veríssimo", 25, 77, 1.91, 28);
        JogadorDeLinha LuizFelipe = new JogadorDeLinha("Luiz Felipe", 27, 79, 1.87, 2);
        JogadorDeLinha FelipeJonatan = new JogadorDeLinha("Felipe Jonatan", 22, 76, 1.77, 3);
        JogadorDeLinha Alison = new JogadorDeLinha("Alison", 27, 70, 1.80, 5);
        JogadorDeLinha DiegoPituca = new JogadorDeLinha("Diego Pituca", 28, 69, 1.75, 21);
        JogadorDeLinha JeanMota = new JogadorDeLinha("Jean Mota", 27, 72, 1.72, 41);
        JogadorDeLinha Marinho = new JogadorDeLinha("Marinho", 30, 65, 1.69, 11);
        JogadorDeLinha Soteldo = new JogadorDeLinha("Soteldo", 23, 55, 1.60, 10);
        JogadorDeLinha KaioJorge = new JogadorDeLinha("Kaio Jorge", 18, 64, 1.76, 19);
        Para.getPosicoes().add("PD");
        LucasVerissimo.getPosicoes().add("ZAG");
        LuizFelipe.getPosicoes().add("ZAG");
        FelipeJonatan.getPosicoes().add("PE");
        Alison.getPosicoes().add("ME");
        DiegoPituca.getPosicoes().add("ME");
        JeanMota.getPosicoes().add("ATA");
        Marinho.getPosicoes().add("ATA");
        Soteldo.getPosicoes().add("ME");
        KaioJorge.getPosicoes().add("ATA");   
        santos.getGoleiros().add(new Goleiro("João Paulo", 25, 86, 1.88, 34));
	santos.getJogadores().add(Para);
        santos.getJogadores().add(LucasVerissimo);
        santos.getJogadores().add(LuizFelipe);
        santos.getJogadores().add(FelipeJonatan);
        santos.getJogadores().add(Alison);
        santos.getJogadores().add(DiegoPituca);
        santos.getJogadores().add(JeanMota);
        santos.getJogadores().add(Marinho);
        santos.getJogadores().add(Soteldo);
        santos.getJogadores().add(KaioJorge);
        
        JogadorDeLinha tche = new JogadorDeLinha("Tche Tche", 30, 64, 1.75, 8);
        JogadorDeLinha dCosta = new JogadorDeLinha("D. Costa", 21, 73, 1.84, 27);
        JogadorDeLinha bAlves = new JogadorDeLinha("B. Alves", 29, 81, 1.84, 3);
        JogadorDeLinha reinaldo = new JogadorDeLinha("Reinaldo", 31, 79, 1.78, 6);
        JogadorDeLinha gSara = new JogadorDeLinha("G. Sara", 11, 71, 1.77, 42);
        JogadorDeLinha luan = new JogadorDeLinha("Luan", 21, 69, 1.75, 13);
        JogadorDeLinha dAlves = new JogadorDeLinha("Dani Alves", 37, 72, 1.72, 10);
        JogadorDeLinha igorGomes = new JogadorDeLinha("I. Gomes", 21, 73, 1.83, 26);
        JogadorDeLinha luciano = new JogadorDeLinha("Luciano", 20, 70, 1.75, 30);
        JogadorDeLinha brenner = new JogadorDeLinha("Brenner", 18, 64, 1.76, 19);
        tche.getPosicoes().add("LD");
        dCosta.getPosicoes().add("ZAG");
        bAlves.getPosicoes().add("ZAG");
        reinaldo.getPosicoes().add("LD");
        gSara.getPosicoes().add("MD");
        luan.getPosicoes().add("VOL");
        dAlves.getPosicoes().add("VOL");
        igorGomes.getPosicoes().add("ME");
        luciano.getPosicoes().add("ATA");
        brenner.getPosicoes().add("ATA");   
        saoPaulo.getGoleiros().add(new Goleiro("T. Volpi", 29, 84, 1.88, 1));
	saoPaulo.getJogadores().add(tche);
        saoPaulo.getJogadores().add(dCosta);
        saoPaulo.getJogadores().add(bAlves);
        saoPaulo.getJogadores().add(reinaldo);
        saoPaulo.getJogadores().add(gSara);
        saoPaulo.getJogadores().add(luan);
        saoPaulo.getJogadores().add(dAlves);
        saoPaulo.getJogadores().add(igorGomes);
        saoPaulo.getJogadores().add(luciano);
        saoPaulo.getJogadores().add(brenner);
        
        JogadorDeLinha patric = new JogadorDeLinha("Patric", 31, 78, 1.72, 2);
        JogadorDeLinha iMaidana = new JogadorDeLinha("I. Maidana", 24, 85, 1.96, 6);
        JogadorDeLinha adryelson = new JogadorDeLinha("Adryelson", 22, 78, 1.82, 34);
        JogadorDeLinha rPrata = new JogadorDeLinha("R. Prata", 33, 75, 1.78, 23);
        JogadorDeLinha rLima = new JogadorDeLinha("R.R de Lima", 31, 77, 1.81, 20);
        JogadorDeLinha marcao = new JogadorDeLinha("Marcao", 29, 78, 1.85, 77);
        JogadorDeLinha lMugni = new JogadorDeLinha("L. Mugni", 28, 76, 1.78, 10);
        JogadorDeLinha mVinicius = new JogadorDeLinha("M. Vinicius", 23, 70, 1.74, 33);
        JogadorDeLinha lBarcia = new JogadorDeLinha("L. Barcia", 28, 71, 1.73, 11);
        JogadorDeLinha tNeves = new JogadorDeLinha("T. Neves", 35, 90, 1.82, 30);
        patric.getPosicoes().add("LD");
        iMaidana.getPosicoes().add("ZAG");
        adryelson.getPosicoes().add("ZAG");
        rPrata.getPosicoes().add("LD");
        rLima.getPosicoes().add("MD");
        marcao.getPosicoes().add("VOL");
        lMugni.getPosicoes().add("VOL");
        mVinicius.getPosicoes().add("ME");
        lBarcia.getPosicoes().add("ATA");
        tNeves.getPosicoes().add("ATA");   
        sport.getGoleiros().add(new Goleiro("L. Polli", 29, 84, 1.88, 1));
	sport.getJogadores().add(patric);
        sport.getJogadores().add(iMaidana);
        sport.getJogadores().add(adryelson);
        sport.getJogadores().add(rPrata);
        sport.getJogadores().add(rLima);
        sport.getJogadores().add(marcao);
        sport.getJogadores().add(lMugni);
        sport.getJogadores().add(tNeves);
        sport.getJogadores().add(mVinicius);
        sport.getJogadores().add(lBarcia);
        
        JogadorDeLinha cTenorio = new JogadorDeLinha("C. Tenorio", 21, 65, 1.72, 2);
        JogadorDeLinha miranda = new JogadorDeLinha("Miranda", 20, 76, 1.82, 25);
        JogadorDeLinha lCastan = new JogadorDeLinha("L. Castan", 35, 80, 1.86, 5);
        JogadorDeLinha henrique = new JogadorDeLinha("Herique", 26, 71, 1.73, 21);
        JogadorDeLinha andrey = new JogadorDeLinha("Andrey", 22, 73, 1.75, 15);
        JogadorDeLinha lGil = new JogadorDeLinha("L. Gil", 29, 65, 1.76, 7);
        JogadorDeLinha vPaiva = new JogadorDeLinha("V. Paiva", 19, 65, 1.70, 28);
        JogadorDeLinha carlinhos = new JogadorDeLinha("Carlinhos", 26, 79, 1.81, 23);
        JogadorDeLinha tMagno = new JogadorDeLinha("T. Magno", 26, 70, 1.86, 11);
        JogadorDeLinha ribamar = new JogadorDeLinha("Ribamar", 23, 81, 1.84, 9);
        
        cTenorio.getPosicoes().add("LD");
        miranda.getPosicoes().add("ZAG");
        lCastan.getPosicoes().add("ZAG");
        henrique.getPosicoes().add("LD");
        andrey.getPosicoes().add("VOL");
        lGil.getPosicoes().add("VOL");
        vPaiva.getPosicoes().add("MD");
        carlinhos.getPosicoes().add("MEI");
        tMagno.getPosicoes().add("ME");
        ribamar.getPosicoes().add("ATA");   
        vasco.getGoleiros().add(new Goleiro("Fernando", 35, 87, 1.91, 1));
	vasco.getJogadores().add(cTenorio);
        vasco.getJogadores().add(miranda);
        vasco.getJogadores().add(lCastan);
        vasco.getJogadores().add(henrique);
        vasco.getJogadores().add(andrey);
        vasco.getJogadores().add(lGil);
        vasco.getJogadores().add(vPaiva);
        vasco.getJogadores().add(carlinhos);
        vasco.getJogadores().add(tMagno);
        vasco.getJogadores().add(ribamar);
	
//------------------------------------------------------------------------------------------------------------------------------
        timesDefault.add(atleticoM);
        timesDefault.add(atleticoG);
        timesDefault.add(atleticoP);
        timesDefault.add(bahia);
        timesDefault.add(botafogo);
        timesDefault.add(ceara);
        timesDefault.add(corinthians);
        timesDefault.add(coritiba);
        timesDefault.add(flamengo);
        timesDefault.add(fluminense);
        timesDefault.add(fortaleza);
        timesDefault.add(goias);
        timesDefault.add(gremio);
        timesDefault.add(inter);
        timesDefault.add(palmeiras);
        timesDefault.add(redBull);
        timesDefault.add(santos);
        timesDefault.add(saoPaulo);
        timesDefault.add(sport);
        timesDefault.add(vasco);
        
        for (int i = 0; i < timesDefault.size(); i++) {
            for(JogadorDeLinha jogador : timesDefault.get(i).getJogadores()){
                jogador.setTime(timesDefault.get(i).getNome());
            }
            for(Goleiro goleiro : timesDefault.get(i).getGoleiros()){
                goleiro.setTime(timesDefault.get(i).getNome());
            }
        }
        
        for (int i = 0; i < timesDefault.size(); i++) {          
            times.add(timesDefault.get(i));
        }
    }

}
